name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DIGITALOCEAN_ID_RSA_CICD_PRIVATE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to Droplet
      run: |
        scp -o StrictHostKeyChecking=no -r ./ ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/var/www/myapp

    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
          cd /var/www/html/cineo_repository
          # Commands to restart your application, e.g.,:
         git pull origin main
        EOF
